### ISSUE TITLE
请问 finetune.ipynb 里面 gpt_weight_pretrain/weight_fp16 这个文件在哪里下载?

### ISSUE THREAD

**Issue by xiewenqian** [bupticybee/ChineseAiDungeon#1]
是这个吗？
├── 80000
│   ├── mp_rank_00_model_states.pt
│   └── mp_rank_01_model_states.pt
└── latest_checkpointed_iteration.txt

**Comment by bupticybee** [comment]
我大约记得是用这个脚本生成的 https://github.com/deepdialog/CPM-LM-TF2/blob/aa43dd058b683d45a07e6d1bea8fd92a4dfa6fa1/load_pytorch-fp16.ipynb

基本来说，使用清源的权重，然后用第三方脚本转成tf格式的
