### ISSUE TITLE
最近有更新吗？

### ISSUE THREAD

**Issue by seasnakes** [bupticybee/ChineseAiDungeon#5]
最近 llm能力应该比之前好很多，大佬有什么更新的计划吗？

**Comment by bupticybee** [comment]
> 最近 llm能力应该比之前好很多，大佬有什么更新的计划吗？

暂时没有更新计划，我认为数据饥荒问题没有被解决，现在LLM作为AI地牢类的潜力其实有限，受限于安全因素，你甚至不能在chatGPT主持的地牢里杀人
